version: "3"

services:
  db:
    image: mysql:8
    restart: always
    cap_add:
      - SYS_NICE
    environment:
      - MYSQL_DATABASE=users_test
      - MYSQL_ROOT_PASSWORD=password
    ports:
       - "4000:3306"
    volumes:
      - ./src/main/resources/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    container_name: java-backend
    restart: 'always'
    build: .
    depends_on:
      - db
    links:
      - db
    ports:
      - "80:8080"
